# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'list-github-repository' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for list-github-repository

  target 'list-github-repositoryTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'list-github-repositoryUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
